### ISSUE TITLE
Can shorten float constants

### ISSUE THREAD

**Issue by programmerjake** [DanielVZ96/spacesort#1]
https://github.com/DanielVZ96/spacesort/blob/d46634a0db747a9d84d2052a0c4a80cdf3d0dfc2/src/lib.rs#L24

Instead of `8.3339 * f64::from(10).powi(-7)`, you can just write `8.3339e-7`. also, instead of `f64::from(10)` you can write `10.0`. If you need the type to be specifically `f64` rather than any float type, you can write `8.3339e-7f64` and `10.0f64`.

**Comment by DanielVZ96** [comment]
Oh, you are right. I totally forgot that notation existed. Thanks for the feedback, I'll clean this asap

**Comment by DanielVZ96** [comment]
Done!
